# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44037c0b6da311d3fe3cf3a96ca391b1ce78dc2b96cb172af96375e6afa6f21b5b3fab03606dafe216eddc407fc8df224544347569664e4711534bc03e0d5227

test:
  secret_key_base: 0254c45a6d9271ac7e12a984b5b46121f9c5d91f6d6167e31c43491197e7a96bb06c1838f2c12d9d6066ffaa82dd51e58bdf9217dbc7aee5b378cde3d8d771ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
